###########
# site.title

title: 'football.db - Open Football Data'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#    note: for root path use empty string e.g. '' - do NOT include trailing slash e.g. /
path:  ''
url:   'http://openfootball.github.io'


remote_theme: openfootball/opendata-theme

########
# more settings

plugins:
- jekyll-feed


markdown: kramdown

sass:
  style:    expanded

exclude:
- README.md
